### ISSUE TITLE
Not works with VS2017

### ISSUE THREAD

**Issue by arteny** [deadlydog/AutoUpdateProjectsMinimumRequiredClickOnceVersion#1]
No any actions performed and no any scripts added after installing package

**Comment by deadlydog** [comment]
Hey @arteny can you provide any more information? I use this NuGet package with VS 2017 and it works just fine. Are you just installing it in a new vanilla project? Are any errors reported in the Visual Studio `Output` window? Is it a regular .Net Framework project, or a .Net Core project?

**Comment by alejob54** [comment]
Hello, I'm not able to find it in VS2017 V15.7.5. Did you remove the nuget package ?

**Comment by deadlydog** [comment]
I've pushed a new version of the NuGet package (v1.0.8), as well as updated the docs a bit. These may fix your issue. I'm going to close this since there's been no response back.
