### ISSUE TITLE
Add support for pubxml files

### ISSUE THREAD

**Issue by TIPConsulting** [deadlydog/AutoUpdateProjectsMinimumRequiredClickOnceVersion#5]
Would it be possible to add support for the new .net Core csproj files and .pubxml publish files?
I'd like to use this tool, but it only recognizes publish rules if they are embedded in the project file.  That is not the standard behavior, publish profiles are now stored in standalone files

The publish profile files can be found here: `$(ProjectDir)Properties\PublishProfiles\`

The target extension is `.pubxml`

To identify ClickOnce publish profiles look for this tag in the pubxml file: `<PublishProtocol>ClickOnce</PublishProtocol>`.  This identifies the profile as a ClickOnce as opposed to folder or Docker profiles

Additionally, it would be very nice for the publish profile to get its version numbers from the csproj file
Example:

- Publish profile versions:
  - `<ApplicationVersion>0.1.0.0</ApplicationVersion>`
  - `<MinimumRequiredVersion>0.1.0.0</MinimumRequiredVersion>`
- csproj version
  - `<Version>0.1.1.0</Version>`

I want to be able to set csproj.Version and have both of the publish profile versions update as well

**Comment by TimKras** [comment]
Any updates about the .pubxml feature?

**Comment by deadlydog** [comment]
Thanks for the suggestion and details. I'm not sure when I'll have time to get to this one, as I'm quite busy these days and have quite a few older free open source tools like this with pending feature requests. I'm happy to accept PRs though.

**Comment by deadlydog** [comment]
Merged and version numbers bumped. Thanks for contributing!

Also, not sure if it would be of interest to you, but there's also this similar repo https://github.com/deadlydog/Set-ProjectFilesClickOnceVersion which can be used in a CI/CD pipeline, as per [my blog](https://blog.danskingdom.com/continuously-deploy-your-clickonce-application-from-your-build-server/). If you decide to use it a similar PR could be made there. Thanks again @TimKras !
